/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2V2;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sebas
 */
public class GUICrear extends javax.swing.JFrame {
    BDBichos bdBichos = new BDBichos();
    /**
     * Creates new form GUIGeneral
     */
    public GUICrear() throws IOException, ClassNotFoundException {
        initComponents(); 
        this.restaurar();
    }
    
    public void validarCampos() throws IOException, FileNotFoundException, ClassNotFoundException{
        
        String nombre = txtNombre.getText();
        int vida, ataque, aparicion, espacio;
        
        String tipo = cmbTipo.getSelectedItem().toString();
        String tipoAtaque = cmbAtaque.getSelectedItem().toString();
        
        String skin = txtImgSkin.getText();
        String imgAtaque = txtImgAtaque.getText();
        
        if(nombre.length() < 1){
            JOptionPane.showMessageDialog(this,"Debe tener un nombre","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            vida = Integer.parseInt(txtVida.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"La vida debe ser un entero","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            ataque = Integer.parseInt(txtAtaque.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"El ataque debe ser un entero","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            espacio = Integer.parseInt(txtEspacio.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"El espacio en vivienda debe ser un entero","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            aparicion = Integer.parseInt(txtNivel.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"El nivel de aparicion debe ser un entero","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        bdBichos.addBicho(new Bicho(nombre,tipoAtaque,skin,imgAtaque,tipo,vida,aparicion,ataque,espacio));
        
        
    }
    
    public void finConfig() throws IOException, FileNotFoundException, ClassNotFoundException{
       guardar();
    }

    
    public void guardar() throws IOException{
        try (ObjectOutputStream escribiendoFichero = new ObjectOutputStream( 
                new FileOutputStream("bichos.txt") )) {
            escribiendoFichero.writeObject(this.bdBichos.getBichos());
        }
    }
    
    public void restaurar() throws IOException, ClassNotFoundException{
        try {
            try (ObjectInputStream leyendoFichero = new ObjectInputStream( 
                    new FileInputStream("bichos.txt") )) {
                ArrayList<Bicho> bd = (ArrayList<Bicho>)leyendoFichero.readObject();
                this.bdBichos.setBichos(bd);
            }
            System.out.println("Base de datos de usuarios cargada.....");
        } catch (IOException | ClassNotFoundException e) {
            System.out.println("Fichero no encontrado");
        }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtNivel = new javax.swing.JTextField();
        lvlVida = new javax.swing.JLabel();
        txtImgAtaque = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblAttackimg = new javax.swing.JLabel();
        lblNivelAp = new javax.swing.JLabel();
        lblSkin = new javax.swing.JLabel();
        txtImgSkin = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblTipoAtt = new javax.swing.JLabel();
        cmbAtaque = new javax.swing.JComboBox<>();
        txtVida = new javax.swing.JTextField();
        lvlAttack = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        txtEspacio = new javax.swing.JTextField();
        txtAtaque = new javax.swing.JTextField();
        lvlNombre = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lvlVida.setText("Vida");

        txtImgAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImgAtaqueActionPerformed(evt);
            }
        });

        jLabel3.setText("Campos");

        lblAttackimg.setText("Imagen Ataque");

        lblNivelAp.setText("Nivel de aparicion");

        lblSkin.setText("Imagen Skin");

        txtImgSkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImgSkinActionPerformed(evt);
            }
        });

        btnAdd.setText("Añadir ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblTipoAtt.setText("Tipo de ataque");

        cmbAtaque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contacto", "Medio alcance", "Largo alcance", "Aereo", " " }));
        cmbAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAtaqueActionPerformed(evt);
            }
        });

        txtVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVidaActionPerformed(evt);
            }
        });

        lvlAttack.setText("Ataque");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zombie", "Artillería", "Muralla" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        txtAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtaqueActionPerformed(evt);
            }
        });

        lvlNombre.setText("Nombre");

        btnAdd1.setText("Finalizar");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvlNombre)
                            .addComponent(lblTipoAtt)
                            .addComponent(lvlVida)
                            .addComponent(jLabel3)
                            .addComponent(lblNivelAp)
                            .addComponent(lblSkin)
                            .addComponent(lblAttackimg, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlAttack))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVida, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImgAtaque, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtImgSkin)
                            .addComponent(txtAtaque)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnAdd)
                        .addGap(88, 88, 88)
                        .addComponent(btnAdd1)))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlAttack)
                    .addComponent(txtAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlVida)
                    .addComponent(txtVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivelAp)
                    .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoAtt)
                    .addComponent(cmbAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSkin)
                    .addComponent(txtImgSkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttackimg)
                    .addComponent(txtImgAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnAdd1))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImgAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImgAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImgAtaqueActionPerformed

    private void txtImgSkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImgSkinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImgSkinActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            validarCampos();
        } catch (IOException ex) {
            Logger.getLogger(GUICrear.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUICrear.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVidaActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtaqueActionPerformed

    }//GEN-LAST:event_txtAtaqueActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        try {
            finConfig();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(GUICrear.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void cmbAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAtaqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUICrear().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GUICrear.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GUICrear.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JComboBox<String> cmbAtaque;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAttackimg;
    private javax.swing.JLabel lblNivelAp;
    private javax.swing.JLabel lblSkin;
    private javax.swing.JLabel lblTipoAtt;
    private javax.swing.JLabel lvlAttack;
    private javax.swing.JLabel lvlNombre;
    private javax.swing.JLabel lvlVida;
    private javax.swing.JTextField txtAtaque;
    private javax.swing.JTextField txtEspacio;
    private javax.swing.JTextField txtImgAtaque;
    private javax.swing.JTextField txtImgSkin;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVida;
    // End of variables declaration//GEN-END:variables
}
