/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2V2;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class LoginUser extends javax.swing.JFrame {
   private BDUsuario usuarios;

    
     public LoginUser() throws IOException, ClassNotFoundException {
        initComponents();
        usuarios = new BDUsuario();
        usuarios.restaurar();
        mostrarUsuarios();
        

    }
     
     public void iniciarJuego() throws IOException, ClassNotFoundException{
          for( Usuario u : usuarios.getUsers()){
              System.out.println(u.getNombre());
              if(txfUsuario.getText().equals(u.getNombre())){
                  GUIUsuario pantalla = new GUIUsuario(u,usuarios);
                  pantalla.setVisible(true);
                  JOptionPane.showMessageDialog(this,"Bienvenido","Aceptado",JOptionPane.DEFAULT_OPTION);
                  return;
              }
              
          }
          Usuario nuevo = new Usuario(txfUsuario.getText());
          usuarios.getUsers().add(nuevo);
          usuarios.guardar();
          JOptionPane.showMessageDialog(this,"Usuario creado exitosamente","Creado",JOptionPane.DEFAULT_OPTION);
          GUIUsuario pantalla = new GUIUsuario(nuevo,usuarios);
          pantalla.setVisible(true);
     }
    
     public void mostrarUsuarios(){
         for(Usuario u: usuarios.getUsers()){
             System.out.println(u.toString());
         }
     }
    
    //cosas del GUIIIIIIIIIIIIIIIIIIIIIIIIII
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txfUsuario = new javax.swing.JTextField();
        lblUsuario1 = new javax.swing.JLabel();
        btnLoguear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 164, 163, -1));

        lblUsuario1.setBackground(new java.awt.Color(51, 51, 255));
        lblUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario1.setText("Usuario");
        jPanel1.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 127, -1, -1));

        btnLoguear1.setBackground(new java.awt.Color(0, 255, 102));
        btnLoguear1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnLoguear1.setText("Login/Register");
        btnLoguear1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnLoguear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoguear1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoguear1MouseExited(evt);
            }
        });
        btnLoguear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoguear1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoguear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 291, -1, 51));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 406, 461));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoguear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoguear1ActionPerformed
        try {
            iniciarJuego();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(LoginUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoguear1ActionPerformed

    private void btnLoguear1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoguear1MouseExited
        btnLoguear1.setBackground(new java.awt.Color(0,255,102));
        btnLoguear1.setForeground(Color.white);
    }//GEN-LAST:event_btnLoguear1MouseExited

    private void btnLoguear1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoguear1MouseEntered
        btnLoguear1.setBackground(Color.WHITE);
        btnLoguear1.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnLoguear1MouseEntered

    private void txfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new LoginUser().setVisible(true);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(LoginUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoguear1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables
}
